[package]
name = "crusty_stocks"
version = "0.0.0"
edition = "2024"
description = "Data Structure for Stock and Crypto Ticker and Candle Data"
license="Beerware"
keywords = ['stock', 'crypto', 'finance', 'candle', 'trading']
categories = ['data-structures']
readme = 'README.md'

[dependencies]
